<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Unhallowed.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Unhallowed.Core\Unhallowed.Core.csproj" />
    <ProjectReference Include="..\Unhallowed.Persistence\Unhallowed.Persistence.csproj" />
  </ItemGroup>

</Project>
